import { route, json } from '../core/http.js';
import { insert, update, find, one, remove, audit } from '../core/store.js';
import { can } from '../core/security.js';
function requireUser(ctx){ if(!ctx.user) throw new Error('Login required'); return ctx.user; }
function requireRole(ctx, role='editor'){ const u=requireUser(ctx); if(!can(u,role)) throw new Error('Forbidden'); return u; }
function money(n){ return Math.round(Number(n||0)*100)/100; }
function calcCart(cart){ const items=cart.items||[]; const subtotal=items.reduce((s,i)=>s+money(i.price)*Number(i.qty||1),0); const discount=money(cart.discount||0); const tax=money((subtotal-discount)*Number(cart.taxRate||0)); const shipping=money(cart.shipping||0); return {...cart,subtotal,discount,tax,shipping,total:money(subtotal-discount+tax+shipping)}; }
export function mountCommerce(){
 route('GET','/api/products',({url,res})=>{ const q=(url.searchParams.get('q')||'').toLowerCase(); let rows=find('products'); if(q) rows=rows.filter(p=>JSON.stringify(p).toLowerCase().includes(q)); return json(res,rows); });
 route('POST','/api/products',(ctx)=>{ const u=requireRole(ctx,'editor'); const p=insert('products',{type:ctx.body.type||'simple',name:ctx.body.name,slug:ctx.body.slug,description:ctx.body.description||'',status:ctx.body.status||'draft',sku:ctx.body.sku,price:money(ctx.body.price),salePrice:ctx.body.salePrice?money(ctx.body.salePrice):null,currency:ctx.body.currency||'GBP',attributes:ctx.body.attributes||{},digital:!!ctx.body.digital,downloadUrl:ctx.body.downloadUrl||null,licenseTemplate:ctx.body.licenseTemplate||null,stockManaged:ctx.body.stockManaged!==false,stock:ctx.body.stock||0,related:ctx.body.related||[],upsells:ctx.body.upsells||[],crossSells:ctx.body.crossSells||[]}); insert('inventory',{productId:p.id,sku:p.sku,stock:p.stock,history:[]}); audit(u.id,'create','product',{id:p.id}); return json(ctx.res,p,201); });
 route('GET','/api/products/:id',({params,res})=>json(res,one('products',p=>p.id===params.id||p.slug===params.id)||{error:'Not found'}));
 route('PATCH','/api/products/:id',(ctx)=>{ const u=requireRole(ctx,'editor'); const p=update('products',ctx.params.id,ctx.body); audit(u.id,'update','product',{id:ctx.params.id}); return json(ctx.res,p); });
 route('DELETE','/api/products/:id',(ctx)=>{ const u=requireRole(ctx,'admin'); remove('products',ctx.params.id); audit(u.id,'delete','product',{id:ctx.params.id}); return json(ctx.res,{ok:true}); });
 route('POST','/api/products/:id/variants',(ctx)=>{ requireRole(ctx,'editor'); return json(ctx.res,insert('productVariants',{productId:ctx.params.id,...ctx.body}),201); });
 route('GET','/api/products/:id/variants',({params,res})=>json(res,find('productVariants',v=>v.productId===params.id)));
 route('POST','/api/inventory/adjust',(ctx)=>{ const u=requireRole(ctx,'editor'); const inv=one('inventory',i=>i.productId===ctx.body.productId||i.sku===ctx.body.sku); if(!inv) return json(ctx.res,{error:'Inventory item not found'},404); const stock=Number(inv.stock||0)+Number(ctx.body.delta||0); const out=update('inventory',inv.id,{stock,history:[...(inv.history||[]),{at:new Date().toISOString(),delta:ctx.body.delta,reason:ctx.body.reason,by:u.id}]}); return json(ctx.res,out); });
 route('POST','/api/carts',(ctx)=>json(ctx.res,insert('carts',calcCart({userId:ctx.user?.id||null,email:ctx.body.email||null,items:[],currency:ctx.body.currency||'GBP'})),201));
 route('POST','/api/carts/:id/items',(ctx)=>{ const cart=one('carts',c=>c.id===ctx.params.id); const product=one('products',p=>p.id===ctx.body.productId); const item={productId:product.id,name:product.name,sku:product.sku,qty:Number(ctx.body.qty||1),price:product.salePrice||product.price}; const out=update('carts',cart.id,calcCart({...cart,items:[...(cart.items||[]),item]})); return json(ctx.res,out); });
 route('PATCH','/api/carts/:id',(ctx)=>{ const cart=one('carts',c=>c.id===ctx.params.id); return json(ctx.res,update('carts',cart.id,calcCart({...cart,...ctx.body}))); });
 route('POST','/api/coupons',(ctx)=>{ requireRole(ctx,'editor'); return json(ctx.res,insert('coupons',ctx.body),201); });
 route('POST','/api/checkout',(ctx)=>{ const cart=one('carts',c=>c.id===ctx.body.cartId); if(!cart) return json(ctx.res,{error:'Cart not found'},404); const order=insert('orders',{cartId:cart.id,userId:ctx.user?.id||cart.userId||null,email:ctx.body.email||cart.email,status:'pending-payment',items:cart.items||[],totals:calcCart(cart),shippingAddress:ctx.body.shippingAddress,billingAddress:ctx.body.billingAddress,paymentProvider:ctx.body.paymentProvider||'manual-local',paymentStatus:'pending',history:[{status:'created',at:new Date().toISOString()}]}); insert('payments',{orderId:order.id,provider:order.paymentProvider,status:'stubbed',amount:order.totals.total,note:'Local adapter only. Add provider code/secrets after Railway deploy if allowed.'}); insert('outbox',{type:'order-created',to:order.email,subject:`Order ${order.id}`,body:JSON.stringify(order,null,2),status:'queued'}); return json(ctx.res,order,201); });
 route('GET','/api/orders',(ctx)=>{ const u=requireUser(ctx); const rows=can(u,'editor')?find('orders'):find('orders',o=>o.userId===u.id); return json(ctx.res,rows); });
 route('PATCH','/api/orders/:id',(ctx)=>{ const u=requireRole(ctx,'editor'); const old=one('orders',o=>o.id===ctx.params.id); const out=update('orders',old.id,{...ctx.body,history:[...(old.history||[]),{status:ctx.body.status||old.status,at:new Date().toISOString(),by:u.id}]}); return json(ctx.res,out); });
 route('POST','/api/orders/:id/refund',(ctx)=>{ requireRole(ctx,'editor'); const o=one('orders',x=>x.id===ctx.params.id); return json(ctx.res,update('orders',o.id,{status:'refunded',refund:{amount:ctx.body.amount||o.totals.total,reason:ctx.body.reason}})); });
 route('POST','/api/subscriptions',(ctx)=>{ requireUser(ctx); return json(ctx.res,insert('subscriptions',{...ctx.body,userId:ctx.user.id,status:'active',provider:'local'}),201); });
 route('POST','/api/reviews',(ctx)=>{ requireUser(ctx); return json(ctx.res,insert('reviews',{...ctx.body,userId:ctx.user.id,status:'pending'}),201); });
 route('GET','/api/reviews/:productId',({params,res})=>json(res,find('reviews',r=>r.productId===params.productId&&r.status==='approved')));
 route('POST','/api/wishlist',(ctx)=>{ requireUser(ctx); return json(ctx.res,insert('wishlists',{userId:ctx.user.id,productId:ctx.body.productId}),201); });
 route('POST','/api/invoices/:orderId',(ctx)=>{ requireRole(ctx,'editor'); const o=one('orders',x=>x.id===ctx.params.orderId); const inv=insert('invoices',{orderId:o.id,number:`INV-${Date.now()}`,status:'issued',total:o.totals.total}); return json(ctx.res,inv,201); });
 route('POST','/api/tax-rules',(ctx)=>{ requireRole(ctx,'admin'); return json(ctx.res,insert('taxRules',ctx.body),201); });
 route('POST','/api/shipping-zones',(ctx)=>{ requireRole(ctx,'admin'); return json(ctx.res,insert('shippingZones',ctx.body),201); });
 route('POST','/api/affiliates',(ctx)=>{ requireRole(ctx,'editor'); return json(ctx.res,insert('affiliates',ctx.body),201); });
 route('GET','/api/commerce/report',(ctx)=>{ requireRole(ctx,'editor'); const orders=find('orders'); const revenue=orders.reduce((s,o)=>s+Number(o.totals?.total||0),0); return json(ctx.res,{orders:orders.length,revenue,products:find('products').length,carts:find('carts').length}); });
}
