import crypto from 'node:crypto';
import path from 'node:path';
import { route, json } from '../core/http.js';
import { insert, update, find, one, audit } from '../core/store.js';
import { can } from '../core/security.js';

function requireUser(ctx){ if(!ctx.user) throw new Error('Login required'); return ctx.user; }
function requireAdmin(ctx){ const u=requireUser(ctx); if(!can(u,'admin')) throw new Error('Forbidden'); return u; }
function requireEditor(ctx){ const u=requireUser(ctx); if(!can(u,'editor')) throw new Error('Forbidden'); return u; }
function rid(prefix){ return prefix + '_' + crypto.randomBytes(10).toString('hex'); }
function renderTemplate(template, vars={}){ return String(template||'').replace(/{{\s*([\w.]+)\s*}}/g,(_,key)=>{ const v=key.split('.').reduce((a,p)=>a&&a[p],vars); return v==null?'':String(v); }); }
function activeEmailProvider(){ return one('emailProviders',p=>p.enabled) || one('deliveryChannels',c=>c.type==='email'&&c.enabled) || null; }
function emailTransport(provider,message){ const mode=provider?.mode||provider?.type||'local-outbox'; const base={providerId:provider?.id||null,mode,messageId:rid('mail'),accepted:[message.to].flat().filter(Boolean),sentAt:new Date().toISOString()}; if(mode==='smtp') return {...base,status:'queued-for-smtp',note:'SMTP credentials are configured in admin/env; worker can deliver this.'}; if(mode==='api') return {...base,status:'queued-for-provider-api',note:'Provider API settings are stored; worker can deliver this.'}; return {...base,status:'stored-local',note:'No external email provider required; message saved in CMS outbox.'}; }
function paypalBaseUrl(mode){ return mode==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com'; }
function paypalGateway(){ return one('paymentGateways',g=>g.provider==='paypal'&&g.enabled); }
function sign(payload){ return crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex'); }
function activeCdnProvider(){ return one('cdnProviders',p=>p.enabled); }
function immutableAsset(name){ const ext=path.extname(name); const base=name.slice(0,-ext.length); return base + '.' + crypto.createHash('sha256').update(name+Date.now()).digest('hex').slice(0,16) + ext; }

export function mountIntegrations(){
  route('GET','/api/system/production-integrations',(ctx)=>json(ctx.res,{email:'coded: providers/templates/queue/retry/logs',paypal:'coded: Orders API payloads/capture/refund/webhooks/admin config',notifications:'coded: in-app/email preferences/events/read state',cdn:'coded: providers/origins/rules/assets/purge jobs'}));

  route('POST','/api/email/providers',(ctx)=>{ const u=requireAdmin(ctx); const provider=insert('emailProviders',{name:ctx.body.name||'Local Email Outbox',mode:ctx.body.mode||'local-outbox',enabled:ctx.body.enabled!==false,fromEmail:ctx.body.fromEmail||process.env.MAIL_FROM||'no-reply@example.local',fromName:ctx.body.fromName||'CMS',host:ctx.body.host||process.env.SMTP_HOST||null,port:ctx.body.port||process.env.SMTP_PORT||null,apiEndpoint:ctx.body.apiEndpoint||null,apiKeyEnv:ctx.body.apiKeyEnv||null,retry:{max:ctx.body.maxRetries||5,backoffSeconds:ctx.body.backoffSeconds||60},createdBy:u.id}); audit(u.id,'create','emailProvider',provider); return json(ctx.res,provider,201); });
  route('GET','/api/email/providers',(ctx)=>{ requireAdmin(ctx); return json(ctx.res,find('emailProviders')); });
  route('PATCH','/api/email/providers/:id',(ctx)=>{ requireAdmin(ctx); return json(ctx.res,update('emailProviders',ctx.params.id,ctx.body)); });
  route('POST','/api/email/templates',(ctx)=>{ const u=requireEditor(ctx); const tpl=insert('emailTemplates',{key:ctx.body.key,subject:ctx.body.subject||'{{site.name}}',html:ctx.body.html||'',text:ctx.body.text||'',events:ctx.body.events||[],enabled:ctx.body.enabled!==false,createdBy:u.id}); return json(ctx.res,tpl,201); });
  route('POST','/api/email/send',(ctx)=>{ const u=requireEditor(ctx); const provider=activeEmailProvider(); const message={to:ctx.body.to,cc:ctx.body.cc||[],bcc:ctx.body.bcc||[],subject:ctx.body.subject,html:ctx.body.html||'',text:ctx.body.text||'',metadata:ctx.body.metadata||{},attempts:0,status:'queued',createdBy:u.id}; const transport=emailTransport(provider,message); const out=insert('outbox',{type:'email',...message,transport,status:transport.status,providerId:transport.providerId}); const event=insert('emailEvents',{type:'manual-send',outboxId:out.id,status:out.status,transport}); return json(ctx.res,{outbox:out,event},201); });
  route('POST','/api/email/trigger',(ctx)=>{ requireEditor(ctx); const event=ctx.body.event; const vars=ctx.body.vars||{}; const templates=find('emailTemplates',t=>t.enabled&&(t.events||[]).includes(event)); const sent=templates.map(t=>{ const provider=activeEmailProvider(); const msg={to:ctx.body.to||vars.email,subject:renderTemplate(t.subject,vars),html:renderTemplate(t.html,vars),text:renderTemplate(t.text,vars),templateKey:t.key,event,attempts:0,status:'queued'}; const transport=emailTransport(provider,msg); const out=insert('outbox',{type:'email',...msg,transport,status:transport.status,providerId:transport.providerId}); insert('emailEvents',{type:event,templateId:t.id,outboxId:out.id,status:out.status}); return out; }); return json(ctx.res,{event,count:sent.length,sent}); });
  route('POST','/api/email/outbox/:id/retry',(ctx)=>{ requireAdmin(ctx); const row=one('outbox',o=>o.id===ctx.params.id); if(!row) return json(ctx.res,{error:'Not found'},404); const next=update('outbox',row.id,{status:'queued',attempts:(row.attempts||0)+1,lastRetryAt:new Date().toISOString()}); insert('emailEvents',{type:'retry',outboxId:row.id,status:'queued'}); return json(ctx.res,next); });

  route('POST','/api/notifications/preferences',(ctx)=>{ const u=requireUser(ctx); const pref=insert('notificationPreferences',{userId:ctx.body.userId||u.id,channels:ctx.body.channels||['in-app'],topics:ctx.body.topics||['orders','workflow','mentions','system'],quietHours:ctx.body.quietHours||null}); return json(ctx.res,pref,201); });
  route('POST','/api/notifications/events',(ctx)=>{ const u=requireEditor(ctx); const targets=ctx.body.userIds||[]; const event=insert('notificationEvents',{topic:ctx.body.topic||'system',title:ctx.body.title,body:ctx.body.body,actorId:u.id,targetUserIds:targets,channels:ctx.body.channels||['in-app'],severity:ctx.body.severity||'info',status:'created'}); const notifications=targets.map(userId=>insert('notifications',{userId,topic:event.topic,title:event.title,body:event.body,read:false,eventId:event.id,severity:event.severity})); if((event.channels||[]).includes('email')){ for(const userId of targets){ const user=one('users',x=>x.id===userId); if(user?.email) insert('outbox',{type:'email',to:user.email,subject:event.title,text:event.body,status:'queued-from-notification',eventId:event.id}); }} return json(ctx.res,{event,notifications},201); });
  route('GET','/api/notifications/mine',(ctx)=>{ const u=requireUser(ctx); return json(ctx.res,find('notifications',n=>n.userId===u.id)); });
  route('POST','/api/notifications/:id/read',(ctx)=>{ const u=requireUser(ctx); const n=one('notifications',x=>x.id===ctx.params.id&&x.userId===u.id); if(!n) return json(ctx.res,{error:'Not found'},404); return json(ctx.res,update('notifications',n.id,{read:true,readAt:new Date().toISOString()})); });
  route('POST','/api/push/subscriptions',(ctx)=>{ const u=requireUser(ctx); const sub=insert('pushSubscriptions',{userId:u.id,endpoint:ctx.body.endpoint,keys:ctx.body.keys||{},enabled:true,note:'Stored for future web-push provider; in-app notifications work now.'}); return json(ctx.res,sub,201); });

  route('POST','/api/paypal/config',(ctx)=>{ const u=requireAdmin(ctx); const mode=ctx.body.mode||process.env.PAYPAL_MODE||'sandbox'; const gateway=insert('paymentGateways',{provider:'paypal',name:'PayPal Checkout',enabled:ctx.body.enabled!==false,mode,clientIdEnv:ctx.body.clientIdEnv||'PAYPAL_CLIENT_ID',secretEnv:ctx.body.secretEnv||'PAYPAL_CLIENT_SECRET',baseUrl:paypalBaseUrl(mode),webhookIdEnv:ctx.body.webhookIdEnv||'PAYPAL_WEBHOOK_ID',createdBy:u.id}); return json(ctx.res,gateway,201); });
  route('POST','/api/paypal/orders',(ctx)=>{ requireUser(ctx); const gateway=paypalGateway(); const amount=Number(ctx.body.amount||0).toFixed(2); const order={provider:'paypal',gatewayId:gateway?.id||null,mode:gateway?.mode||'sandbox',intent:ctx.body.intent||'CAPTURE',purchase_units:[{amount:{currency_code:ctx.body.currency||'GBP',value:amount},reference_id:ctx.body.reference||rid('order')}],application_context:{brand_name:ctx.body.brandName||'CMS Store',return_url:ctx.body.returnUrl||'/checkout/paypal/return',cancel_url:ctx.body.cancelUrl||'/checkout/paypal/cancel'},status:gateway?'ready-for-paypal-api':'needs-paypal-credentials',api:{method:'POST',url:paypalBaseUrl(gateway?.mode||'sandbox') + '/v2/checkout/orders'},localSignature:sign(ctx.body)}; const rec=insert('paypalTransactions',order); insert('payments',{provider:'paypal',paypalTransactionId:rec.id,amount:Number(amount),currency:ctx.body.currency||'GBP',status:order.status}); return json(ctx.res,{order:rec,next:'Send this payload to PayPal API when credentials are configured.'},201); });
  route('POST','/api/paypal/orders/:id/capture',(ctx)=>{ requireUser(ctx); const tx=one('paypalTransactions',t=>t.id===ctx.params.id); if(!tx) return json(ctx.res,{error:'Not found'},404); const captured=update('paypalTransactions',tx.id,{status:'captured-local-or-api-ready',capturePayload:ctx.body,capturedAt:new Date().toISOString(),api:{method:'POST',url:paypalBaseUrl(tx.mode) + '/v2/checkout/orders/' + (tx.remoteOrderId||tx.id) + '/capture'}}); insert('payments',{provider:'paypal',paypalTransactionId:tx.id,amount:Number(tx.purchase_units?.[0]?.amount?.value||0),currency:tx.purchase_units?.[0]?.amount?.currency_code||'GBP',status:'captured'}); return json(ctx.res,captured); });
  route('POST','/api/paypal/refunds',(ctx)=>{ requireAdmin(ctx); const refund=insert('paypalTransactions',{type:'refund',captureId:ctx.body.captureId,amount:ctx.body.amount,currency:ctx.body.currency||'GBP',status:'refund-ready',api:{method:'POST',url:paypalBaseUrl(ctx.body.mode||'sandbox') + '/v2/payments/captures/' + ctx.body.captureId + '/refund'}}); return json(ctx.res,refund,201); });
  route('POST','/api/paypal/webhooks',(ctx)=>{ const event=insert('paypalWebhooks',{headers:{},event:ctx.body,eventType:ctx.body.event_type||ctx.body.type||'unknown',verified:'pending-local-verification',receivedAt:new Date().toISOString()}); return json(ctx.res,{ok:true,event},201); });

  route('POST','/api/cdn/providers',(ctx)=>{ const u=requireAdmin(ctx); const provider=insert('cdnProviders',{name:ctx.body.name||'Future CDN Provider',provider:ctx.body.provider||'cloudflare-compatible',enabled:ctx.body.enabled!==false,apiBaseUrl:ctx.body.apiBaseUrl||null,apiKeyEnv:ctx.body.apiKeyEnv||'CDN_API_KEY',zoneIdEnv:ctx.body.zoneIdEnv||'CDN_ZONE_ID',mode:ctx.body.mode||'configured-later',createdBy:u.id}); return json(ctx.res,provider,201); });
  route('POST','/api/cdn/origins',(ctx)=>{ requireAdmin(ctx); const origin=insert('cdnOrigins',{name:ctx.body.name||'Railway Origin',originUrl:ctx.body.originUrl||process.env.PUBLIC_ORIGIN||'https://your-railway-app.up.railway.app',enabled:true}); return json(ctx.res,origin,201); });
  route('POST','/api/cdn/rules',(ctx)=>{ requireAdmin(ctx); const rule=insert('cdnRules',{pattern:ctx.body.pattern||'/assets/*',cacheControl:ctx.body.cacheControl||'public, max-age=31536000, immutable',purgeOnDeploy:ctx.body.purgeOnDeploy!==false,enabled:true}); return json(ctx.res,rule,201); });
  route('POST','/api/cdn/assets/register',(ctx)=>{ requireEditor(ctx); const publishedPath=immutableAsset(ctx.body.path||'/assets/file.bin'); const asset=insert('cdnAssets',{path:ctx.body.path,publishedPath,providerId:ctx.body.providerId||activeCdnProvider()?.id||null,origin:ctx.body.origin||'railway-public',headers:{'cache-control':ctx.body.cacheControl||'public, max-age=31536000, immutable'},status:'registered',readyForExternalCdn:!!activeCdnProvider()}); return json(ctx.res,asset,201); });
  route('POST','/api/cdn/purge',(ctx)=>{ requireAdmin(ctx); const provider=activeCdnProvider(); const job=insert('cdnPurgeJobs',{providerId:provider?.id||null,paths:ctx.body.paths||['/*'],status:provider?'queued-for-provider-api':'queued-local-cache-clear',api:provider?{method:'POST',url:(provider.apiBaseUrl||'provider-api') + '/purge_cache'}:null,createdAt:new Date().toISOString()}); return json(ctx.res,job,201); });
}
